// Mocks generated by Mockito 5.4.2 from annotations
// in new_app/test/features/photo_viewer/data/photo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:new_app/features/photo_viewer/data/datasource/buffer_photos_data_source.dart'
    as _i5;
import 'package:new_app/features/photo_viewer/data/datasource/dolphin_photo_data_source.dart'
    as _i3;
import 'package:new_app/features/photo_viewer/data/model/photo_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePhotoModel_0 extends _i1.SmartFake implements _i2.PhotoModel {
  _FakePhotoModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PhotoDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoDataSource extends _i1.Mock implements _i3.PhotoDataSource {
  MockPhotoDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PhotoModel> getPhoto() => (super.noSuchMethod(
        Invocation.method(
          #getPhoto,
          [],
        ),
        returnValue: _i4.Future<_i2.PhotoModel>.value(_FakePhotoModel_0(
          this,
          Invocation.method(
            #getPhoto,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PhotoModel>);
}

/// A class which mocks [BufferPhotosDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBufferPhotosDataSource extends _i1.Mock
    implements _i5.BufferPhotosDataSource {
  MockBufferPhotosDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PhotoModel>> getBufferedPhotos() => (super.noSuchMethod(
        Invocation.method(
          #getBufferedPhotos,
          [],
        ),
        returnValue: _i4.Future<List<_i2.PhotoModel>>.value(<_i2.PhotoModel>[]),
      ) as _i4.Future<List<_i2.PhotoModel>>);

  @override
  void updateBuffer(_i2.PhotoModel? photoModel) => super.noSuchMethod(
        Invocation.method(
          #updateBuffer,
          [photoModel],
        ),
        returnValueForMissingStub: null,
      );
}
